### ISSUE TITLE
args

### ISSUE THREAD

**Issue by I8087** [I8087/mlib#6]
`argc` and `argv` aren't handled properly in `crt0.asm`.

**Comment by ghost** [comment]
You should split the arguments into tokens are put a null pointer before and after.

The reason for before:

> If  the  value  of argc is  greater than  zero, the string pointed to by argv[0] represents  the program name argv[0][0] shall be the null character if the program name is not available from the host  environment.

C11 tells us that argv[0] should be the program name if available or a null otherwise. Since MikeOS does not provide a program name in the arguments you should just pass a null. You could also do some kind of preprocessor trickery to get the program name.

The reason for after:

> argv[argc] shall be a null pointer.

So you need a null pointer to terminate the list.

I should probably fix my code with regards to this.

**Comment by I8087** [comment]
Done, I'll push the commit shortly and close this problem.

> You could also do some kind of preprocessor trickery to get the program name.

This would be the best way to get it done. The closest I could get to something like that though is nasm's `__FILE__`, which would just expand to `crt0.asm` (The current file). I searched around in the manual; I found `__OUTPUT_FORMAT__` but no `__OUTPUT_FILE__`.
